In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Titanic-Dataset.csv")

In [25]:
# A.
df1=df[["Name","Sex","Age","Fare","Survived"]]

# B.
df2=df[(df["Sex"]== "female") & (df["Fare"]>30)][["Name","Sex","Age","Fare","Survived"]]

# C.
result = df.groupby("Pclass").agg({
    "Survived": "mean",
    "Fare": "mean",
    "Age": "mean"
})

result = result.rename(columns={      # Rename columns
    "Survived": "Survival Rate",
    "Fare": "Average Fare",
    "Age": "Average Age"
})
print(result)

        Survival Rate  Average Fare  Average Age
Pclass
1            0.629630     84.154687    38.233441
2            0.472826     20.662183    29.877630
3            0.242363     13.675550    25.140620

In [21]:
df1

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

In [22]:
df2

,Name,Sex,Age,Fare,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,1
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,31.3875,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,146.5208,1
...,...,...,...,...,...
853,"Lines, Miss. Mary Conover",female,16.0,39.4000,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,164.8667,1
863,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,69.5500,0
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,52.5542,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,83.1583,1

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q