### Data Concatenation

Data concatenation is used to combine multiple DataFrames either **row-wise** or **column-wise**.

* **Row-wise Concatenation**
  Combines rows from multiple DataFrames into a single DataFrame. By default, the original indexes are preserved.

* **Ignore Index**
  Resets the index after concatenation and creates a new sequential index.

* **Column-wise Concatenation**
  Combines DataFrames side by side by adding columns. Each DataFrame is aligned based on their index.

In [1]:
import pandas as pd

In [2]:
#Data Concatenation

df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["Sayan","Samata","Sreenika"]
})

df2=pd.DataFrame({
    "id":[4,5,6],
    "name":["Lakshmi Narayan","Manju","Aayansh"]
})

pd.concat([df1,df2]) #row wise concatenation
pd.concat([df1,df2],ignore_index=True) # ignore_index=True creates a new sequential index

pd.concat([df1,df2],axis=1) #column wise concatenation

   id      name  id             name
0   1     Sayan   4  Lakshmi Narayan
1   2    Samata   5            Manju
2   3  Sreenika   6          Aayansh

In [3]:
df1

   id      name
0   1     Sayan
1   2    Samata
2   3  Sreenika

In [4]:
df2

   id             name
0   4  Lakshmi Narayan
1   5            Manju
2   6          Aayansh