### Merging and Joining Data

Merging is used to combine two DataFrames based on a common column.

* **Inner Join**
  Returns only the rows where the key column exists in both DataFrames.

* **Left Join**
  Returns all rows from the left DataFrame and the matching rows from the right DataFrame. Non-matching values from the right side become `NaN`.

* **Right Join**
  Returns all rows from the right DataFrame and the matching rows from the left DataFrame. Non-matching values from the left side become `NaN`.

* **Outer Join**
  Returns all rows from both DataFrames. If a match is not found in either DataFrame, the missing values are filled with `NaN`.

In [1]:
import pandas as pd

In [2]:
#Merging and Joining Data
df_customers = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name": ["Adam", "Bob","Charlie", "Dave"]
})

df_orders=pd.DataFrame({
    "order_id":[101,102,103,104],
    "customer_id":[2,1,4,5],
    "amount":[250,120,300,180]
})

# INNER JOIN → Returns only matching customer_id present in both DataFrames
pd.merge(df_customers,df_orders,on="customer_id") #inner join

# LEFT JOIN → Returns all records from left DataFrame (df_customers) and matching records from df_orders
pd.merge(df_customers,df_orders,on="customer_id",how="left") #left join

# RIGHT JOIN → Returns all records from right DataFrame (df_orders) and matching records from df_customers
pd.merge(df_customers,df_orders,on="customer_id",how="right") #Right join

# OUTER JOIN → Returns all records from both DataFrames and Missing matches will contain NaN values
pd.merge(df_customers,df_orders,on="customer_id",how="outer") #Outer join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [3]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [4]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180